#+TITLE: Prachi's Corrections for Input Use and Labour
#+PROPERTY: header-args:R :eval never-export :session labour
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+HTML_HEAD: <style>#content{max-width:1200px;} </style>
#+MACRO: hlmacro (eval (org-table-insert-hline))

#+NAME: read-data
#+BEGIN_SRC R :results value silent :exports none :session labour
  require(RPostgreSQL)
  source("sserconnect.R")
#+END_SRC


* Guidelines for data entry

+ If information on number of days men/women/children worked is given when contract was on piece rate basis- it should be entered in labour days column.

+ Check cropping pattern to verify if any fodder crop was grown. If it is grown the labour use should be entered for such crops.

+ Entry for loading, unloading and  transporting the produce to home (at least, if not market) should be made for each crop (not for fodder crop)

+ In case of fodder crops, harvesting days should be entered. Based on standard in the village.

+ If harvesting is done using combine, entry for threshing should not be there
+ If harvesting is done by hand, mandatory entry for threshing
+ If crop is destroyed, an entry should exist in the cropping pattern.
+ In case of Wheat crop, an entry for reaper should be made if the crop was cut by combine.
+ In case of threshing, an entry for threshing machine operator and an additional entry for manual labour which is hired plus family labour if they engage in agricultural work should be made for accounting the work of loading etc done during threshing.
+ NOTE that machine hours are total hours, not daily hours
+ If children have been reported to work in the field, necessary adjustment in labour use is to be made.
+ Add "999" in case the information is missing
+ All codes should be entered in ascending order.
+ NOTE: All inputs that are used for a particular crop should have an equivalent entry in labour use. For example an entry for applying manure must exist if manure is reported in input use. Check the same for spray, fertilisers, pesticides etc.

+ For entering data on machinery, one entry for the operator, one for the machine and one for any extra manual labour that was used should be made separately.

* Programs for checking
#+NAME: load-libraries
#+BEGIN_SRC R :results silent :exports none
  require(RPostgreSQL)
  require(ggplot2)
  require(data.table)
    addhead<-function(d1,v1,v2) {
          CJ(unique(v1),unique(v2))->tabhead
           c(1:nrow(tabhead))->tabhead$rank
           ave(tabhead$rank,tabhead$V1,FUN=rank)->tabhead$rank
           ave(tabhead$rank,tabhead$V1,FUN=length)->tabhead$len
           tabhead$V1[tabhead$rank!=1]<-""
           ifelse(tabhead$V1=="","",paste("<",tabhead$len,"colc>",tabhead$V1,sep=""))->tabhead$V1
           transpose(tabhead[,c(1:2)])->tabhead
           as.data.frame(rbind(tabhead,d1,fill=TRUE))->tabhead2
           levels(tabhead2[,ncol(tabhead2)])<-c(levels(tabhead2[,ncol(tabhead2)]),names(tabhead2)[length(names(tabhead2))],"{{{hlmacro}}}")
           names(tabhead2)[length(names(tabhead2))] ->tabhead2[1,ncol(tabhead2)]
           "{{{hlmacro}}}"->tabhead2[2,ncol(tabhead2)]
           tabhead2[,c(ncol(tabhead2),1:ncol(tabhead2)-1)]->tabhead2
  #         tabhead2[2,1]<-""
          tabhead2
      }

#+END_SRC

#+NAME: read-data-code
#+BEGIN_SRC R :results silent :exports none
    dbListTables(surveypg)->t

    data.table(dbReadTable(surveypg,"ruralsurvey_household"))->household
    data.table(dbReadTable(surveypg,"ruralsurvey_sampledesign"))->sampledesign
    data.table(dbReadTable(surveypg,"ruralsurvey_member"))->member
    data.table(dbReadTable(surveypg,"ruralsurvey_codecaste"))->castes
    data.table(dbReadTable(surveypg,"ruralsurvey_codevillage"))->villages
    data.table(dbReadTable(surveypg,"ruralsurvey_coderelationship"))->relationship
    data.table(dbReadTable(surveypg,"ruralsurvey_codeoccupationcategory"))->occupationcode
    data.table(dbReadTable(surveypg,"ruralsurvey_occupations_household_members"))->occupations
    data.table(dbReadTable(surveypg,"ruralsurvey_current_ownership_holdings"))->land
    data.table(dbReadTable(surveypg,"ruralsurvey_irrigation_ownership_holdings"))->irrigation
    data.table(dbReadTable(surveypg,"ruralsurvey_cropping_pattern_schedule_production_and_sales"))->crop
    sampledesign[,id:=NULL]
    data.table(dbReadTable(surveypg,"ruralsurvey_input_use_for_crops_crop_number"))->input
    data.table(dbReadTable(surveypg,"ruralsurvey_input_use_for_crops"))->cropinput
    data.table(dbReadTable(surveypg,"ruralsurvey_codeinputtype"))->input_type
    data.table(dbReadTable(surveypg,"ruralsurvey_labour_days_employed_and_wage_rates_agri"))->labouruse
    data.table(dbReadTable(surveypg,"ruralsurvey_codeinputcategory"))->input_category
  data.table(dbReadTable(surveypg,"ruralsurvey_codelabourunit"))->measurement_unit
    merge(household,sampledesign,by=c("village_id","stratum_number"),all.x=T)->household
    household[is.na(multiplier),multiplier:=1]
    #dbDisconnect(surveypg)

#+END_SRC
* Missing input data
#+NAME: missing-data-code
#+BEGIN_SRC R :results value :exports results :colnames yes :hline yes
  merge(household,villages,by.x="village_id",by.y="id")->t
  t[,.(village_name,household_number,id)]->t

  merge(crop,t,by.x="sno_id",by.y="id",all.y=TRUE)->t
  t[!is.na(crop_number)]->t
  merge(t,input,by.x="id",by.y="cropping_pattern_schedule_production_and_sales_id")->t

  merge(t,cropinput,by.x="input_use_for_crops_id",by.y="id")->t
  merge(t,input_type,by.x="input_type_id",by.y="id",all.x=TRUE)->t
  merge(t,input_category,by.x="input_category_id",by.y="id",all.x=TRUE)->t
  t[is.na(source),.(village_name,household_number,serial_number,balnkfield="source",input_category,input_type)]->t1
  t[input_category=="Chemical fertiliser" & is.na(input_type),.(village_name,household_number,serial_number,balnkfield="input_type",input_category,input_type)]->t2
  rbind(t1,t2)->t3
  t3[order(village_name,household_number)]->t3
  t3
#+END_SRC

#+RESULTS: missing-data-code
| village_name | household_number | serial_number | balnkfield | input_category            | input_type |
|--------------+------------------+---------------+------------+---------------------------+------------|
| Gijji        |               43 |             4 | source     | Water                     | nil        |
| Gijji        |               43 |             7 | source     | Water                     | nil        |
| Gijji        |               45 |             5 | source     | Water                     | nil        |
| Gijji        |               45 |             7 | source     | Water                     | nil        |
| Gijji        |               45 |            10 | source     | Water                     | nil        |
| Gijji        |               47 |             5 | source     | Water                     | nil        |
| Gijji        |               47 |             7 | source     | Water                     | nil        |
| Gijji        |               47 |            10 | source     | Water                     | nil        |
| Gijji        |               47 |             6 | source     | Seed/Planting material    | nil        |
| Gijji        |               48 |            11 | source     | Plant protection chemical | nil        |
| Gijji        |               48 |             6 | source     | Water                     | nil        |
| Gijji        |               48 |            12 | source     | Water                     | nil        |
| Gijji        |               71 |             4 | source     | Water                     | nil        |
| Gijji        |               71 |             7 | source     | Water                     | nil        |
| Gijji        |               72 |             2 | source     | nil                       | nil        |
| Gijji        |               72 |             5 | source     | nil                       | nil        |
| Gijji        |               72 |            10 | source     | Plant protection chemical | nil        |
| Gijji        |               72 |            11 | source     | Water                     | nil        |
| Gijji        |               72 |            15 | source     | Water                     | nil        |
| Gijji        |               74 |             2 | source     | Chemical fertiliser       | Urea       |
| Gijji        |               74 |             1 | source     | Seed/Planting material    | nil        |
| Gijji        |               77 |             6 | source     | Water                     | nil        |
| Gijji        |               77 |             9 | source     | Water                     | nil        |
| Gijji        |               77 |            12 | source     | Water                     | nil        |
| Gijji        |               77 |            16 | source     | Water                     | nil        |
| Gijji        |               77 |             5 | source     | Seed/Planting material    | nil        |
| Gijji        |               77 |             8 | source     | Seed/Planting material    | nil        |
| Gijji        |               77 |            11 | source     | Seed/Planting material    | nil        |
| Gijji        |               77 |            15 | source     | Seed/Planting material    | nil        |
| Gijji        |               77 |            17 | source     | Seed/Planting material    | nil        |
| Gijji        |               85 |            14 | source     | Plant protection chemical | nil        |
| Gijji        |               85 |             5 | source     | Water                     | nil        |
| Gijji        |               85 |             7 | source     | Water                     | nil        |
| Gijji        |               85 |            11 | source     | Water                     | nil        |
| Gijji        |               85 |            15 | source     | Water                     | nil        |
| Gijji        |               85 |             3 | source     | Seed/Planting material    | nil        |
| Gijji        |               85 |            13 | source     | Seed/Planting material    | nil        |
| Gijji        |               96 |            23 | source     | Plant protection chemical | nil        |
| Gijji        |               96 |            24 | source     | Water                     | nil        |

#+NAME: missing-data-code-2
#+BEGIN_SRC R :results value :exports results :colnames yes :hline yes
  merge(household,villages,by.x="village_id",by.y="id")->t
  t[,.(village_name,household_number,id)]->t

  merge(crop,t,by.x="sno_id",by.y="id",all.y=TRUE)->t
  t[!is.na(crop_number)]->t
  merge(t,input,by.x="id",by.y="cropping_pattern_schedule_production_and_sales_id")->t

  merge(t,cropinput,by.x="input_use_for_crops_id",by.y="id")->t
  merge(t,input_type,by.x="input_type_id",by.y="id",all.x=TRUE)->t
  merge(t,input_category,by.x="input_category_id",by.y="id",all.x=TRUE)->t
  merge(t,labouruse,by.x=c("sno_id","crop_id"),by.y=c("sno_id","crop_id"))->p

  p[is.na(crop_operation_code),.(village_name,household_number,crop_no,blankfield="crop_operation_code",crop_operation_stage)]->t1
  p[is.na(crop_operation_stage),.(village_name,household_number,crop_no,blankfield="crop_operation_stage",crop_operation_code)]->t2
  p[is.na(crop_no),.(village_name,household_number,blankfield="crop_no",crop_operation_code,"crop_operation_stage")]->t3


  p[type_of_worker=="Piece-rated workers"& measurement_unit_id==1,.(village_name,household_number,crop_no,blankfield="crop_operation_code")]->s # fixing piece rate





  rbind(t1,t2,t3,fill=TRUE)->p1


  t[is.na(source),.(village_name,household_number,serial_number,blankfield="source",input_category,input_type)]->t1


  t[input_category=="Plant protection chemical"& is.na(input_type),.(village_name,household_number,serial_number,balnkfield="input_type",input_category,input_type)]->t2
  rbind(t1,t2)->t3
  t3[order(village_name,household_number)]->t3
  t3
#+END_SRC



#+NAME: missing-data-code-3
#+BEGIN_SRC R :results value :exports results :colnames yes :hline yes
  merge(household,villages,by.x="village_id",by.y="id")->t
  t[,.(village_name,household_number,id)]->t

  merge(crop,t,by.x="sno_id",by.y="id",all.y=TRUE)->t
  t[!is.na(crop_number)]->t
  merge(t,labouruse,by.x=c("sno_id","crop_id"),by.y=c("sno_id","crop_id"))->p
  p[type_of_worker=="Piece-rated workers"& measurement_unit_id==1,.(village_name,household_number,crop_no)]->s # fixing piece rate
  s
#+END_SRC


#+CAPTION: The table has piece rate contract but measurement unit is days. 
#+RESULTS: missing-data-code-3
| village_name     | household_number | crop_no |
|------------------+------------------+---------|
| Jamalpur Shekhan |                5 |       1 |
| Jamalpur Shekhan |                9 |       2 |
| Jamalpur Shekhan |                9 |       1 |
| Jamalpur Shekhan |               10 |       2 |
| Jamalpur Shekhan |               10 |       1 |
| Jamalpur Shekhan |               10 |       1 |
| Jamalpur Shekhan |               16 |       4 |
| Jamalpur Shekhan |               19 |       5 |
| Jamalpur Shekhan |               19 |       2 |
| Jamalpur Shekhan |               25 |       1 |
| Jamalpur Shekhan |               25 |       1 |
| Jamalpur Shekhan |               31 |       2 |
| Jamalpur Shekhan |               33 |       6 |
| Jamalpur Shekhan |               33 |       6 |
| Jamalpur Shekhan |               33 |       2 |
| Jamalpur Shekhan |               33 |       2 |
| Jamalpur Shekhan |               33 |       2 |
| Jamalpur Shekhan |               34 |       3 |
| Jamalpur Shekhan |               34 |       3 |
| Jamalpur Shekhan |               34 |       4 |
| Jamalpur Shekhan |               34 |       4 |
| Jamalpur Shekhan |               34 |       2 |
| Jamalpur Shekhan |               40 |       2 |
| Jamalpur Shekhan |               41 |       2 |
| Jamalpur Shekhan |               48 |       4 |
| Jamalpur Shekhan |               48 |       1 |
| Jamalpur Shekhan |               48 |       1 |
| Jamalpur Shekhan |               48 |       1 |



#+NAME: missing-data-code-4
#+BEGIN_SRC R :results value :exports results :colnames yes :hline yes
  merge(household,villages,by.x="village_id",by.y="id")->t
  t[,.(village_name,household_number,id)]->t

  merge(crop,t,by.x="sno_id",by.y="id",all.y=TRUE)->t
  t[!is.na(crop_number)]->t
  merge(t,input,by.x="id",by.y="cropping_pattern_schedule_production_and_sales_id")->t

  merge(t,cropinput,by.x="input_use_for_crops_id",by.y="id")->t
  merge(t,input_type,by.x="input_type_id",by.y="id",all.x=TRUE)->t
  merge(t,input_category,by.x="input_category_id",by.y="id",all.x=TRUE)->t
  merge(t,labouruse,by.x=c("sno_id","crop_id"),by.y=c("sno_id","crop_id"))->p

  p[is.na(crop_operation_code),.(village_name,household_number,crop_no,blankfield="crop_operation_code",crop_operation_stage)]->t1
  p[is.na(crop_operation_stage),.(village_name,household_number,crop_no,blankfield="crop_operation_stage",crop_operation_code)]->t2
  p[is.na(crop_no),.(village_name,household_number,blankfield="crop_no",crop_operation_code,"crop_operation_stage")]->t3


  p[type_of_worker=="Piece-rated workers"& measurement_unit_id==1,.(village_name,household_number,crop_no,blankfield="crop_operation_code")]->s # fixing piece rate





  rbind(t1,t2,t3,fill=TRUE)->p1


  t[is.na(source),.(village_name,household_number,serial_number,blankfield="source",input_category,input_type)]->t1


  t[input_category=="Plant protection chemical"& is.na(input_type),.(village_name,household_number,serial_number,balnkfield="input_type",input_category,input_type)]->t2
  rbind(t1,t2)->t3
  t3[order(village_name,household_number)]->t3
  t3
#+END_SRC



